// ------------------------------------------------------------------
//   sam_bismark.c
//   Copyright (C) 2022-2022 Genozip Limited
//   Please see terms and conditions in the file LICENSE.txt

// Compresses auxilliary fields generated by Bismark

#include "genozip.h"
#include "sam_private.h"
#include "strings.h"
#include "reference.h"
#include "segconf.h"
#include "seg.h"
#include "piz.h"
#include "reconstruct.h"

static inline rom XG_prediction (VBlockSAMP vb, SamFlags f, int magic_number) 
{ 
    if (!f.multi_segs || f.is_first != f.rev_comp)
        return (vb->c2t_minus_g2a > 0) ? "CT" : "GA"; 
    
    else
        return (vb->c2t_minus_g2a > magic_number) ? "CT" : "GA"; 
}

// 2 possible values: G C
void sam_seg_bismark_XG_Z (VBlockSAMP vb, ZipDataLineSAM *dl, STRp(xg), unsigned add_bytes)
{
    const int magic_number = 7; // magic number discovered through trial and error
    rom p = XG_prediction (vb, dl->FLAG, magic_number);

    if (xg_len == 2 && xg[0] == p[0] && xg[1] == p[1]) 
        seg_by_did (VB, (char[]){ SNIP_SPECIAL, SAM_SPECIAL_BISMARK_XG, 100 + magic_number }, 3, OPTION_XG_Z, add_bytes);

    else 
        // note: prediction sometimes fails when both c2t and g2a are near-0, eg "c2t=1 g2a=2" or "c2t=0 g2a=2"
        seg_by_did (VB, STRa(xg), OPTION_XG_Z, add_bytes);
}

SPECIAL_RECONSTRUCTOR (sam_piz_special_BISMARK_XG)
{
    if (reconstruct) 
        RECONSTRUCT (XG_prediction (VB_SAM, last_flags, (int8_t)*snip - (int8_t)100), 2);

    return NO_NEW_VALUE;
}
