// ------------------------------------------------------------------
//   text-license.h
//   Copyright (C) 2019-2022 Genozip Limited
//   Please see terms and conditions in LICENSE.txt

#include "version.h"

static rom license[] = {
    "This program, \"Genozip\", which includes four tools (genozip, genounzip, genocat and genols), source code, object code, executables, documentation and other files, was developed by Divon Lan (\"Developer\") and is copyright (C) 2019-2022 Genozip Limited (\"Licensor\"). All rights reserved.",
    "TERMS AND CONDITIONS FOR USE",
    "1. Definitions.",
    "\"License\" shall mean the terms and conditions for use as defined by Sections 1 through 7 of this document.",

    "\"Legal Entity\" shall mean the union of the acting entity and all other entities that control, are controlled by, or are under common control with that entity. For the purposes of this definition, \"control\" means (i) the power, direct or indirect, to cause the direction or management of such entity, whether by contract or otherwise, or (ii) ownership of fifty percent (50%) or more of the outstanding shares, or (iii) beneficial ownership of such entity.",

    "\"You\" (or \"Your\") shall mean an individual or Legal Entity exercising permissions granted by this License.",

    "\"Derivative Works\" shall mean any work that is based on (or derived from) Genozip and for which the editorial revisions, annotations, elaborations, or other modifications represent, as a whole, an original work of authorship. For the purposes of this License, Derivative Works shall not include works that remain separable from Genozip and Derivative Works thereof.",

    "\"Clinical Data\" shall mean any data obtained by sequencing DNA or RNA with the intent of providing a direct clinical benefit to the individual who provided the sample, for example via better diagnosis or treatment; any data generated by processing Clinical Data is also Clinical Data.",
    
    "Other words and terms in this License shall be interpreted as their usual meaning in the context of a software product.",

    "2. Grant of copyright license. Licensor hereby grants to You a limited non-exclusive copyright license to use Genozip for any the following limited purposes subject to the conditions attached to each purpose, and subject to the terms and conditions of this License:",
    "   a. For academic research, educational or training purposes, but excluding use with Clinical Data.",
    "   b. For another non-commercial purpose, if it has been pre-approved by Licensor in writing. Email "EMAIL_REGISTER" to seek such an approval.",
    "   c. For any legal purpose, if a Commercial License was purchased and paid for, and for the duration that it is in effect. For details, see https://genozip.com/commercial.html or email "EMAIL_SALES".",
    "   d. For any legal purpose, if use is limited to the three tools: genounzip, genocat, genols.",
    "   e. For the purpose of evaluating Genozip, for a duration of 30 days.",
    "   f. For the purpose of distributing Genozip to others via a platform that is free of charge, including (but not limited to) an Internet website, a package or container management system, or a module on an institutional HPC.",
    
    "3. Additional Terms and conditions",
    "   a. You must fully and accurately complete the registration, either by completing the registeration as prompted by the genozip tool or by receiving registration confirmation after registering by emailing "EMAIL_REGISTER".",
    "   b. Using Genozip to compress a file is only permitted if the file is retained in its original form as well or the potential loss of data due to Genozip not being able to uncompress the compressed file would not cause any harm.",
    "   c. Any changes to the Genozip's source code and/or creation of Derivative Works are not permitted, unless prior written permission is obtained from Licensor.",
    "   d. Any software source code intentionally submitted for inclusion in Genozip by You to the Licensor or the Developer, including by using a Github Pull Request, shall imply complete and irrevocable assignment by You to Licensor of all copyright in the submitted source code. Regarding any such source code You submitted for inclusion in Genozip in the past, You hereby assign all copyright in this submitted source code to Licensor.",

    "4. Severely unauthorized use of Genozip. Use which is non-compliant with sections 2, 3a, 3c shall be considered severely unauthorized use of Genozip. In this case, You agree that Licensor shall be eligible to 20% ownership of any revenue generated and intellectual property created that involved the severely unauthorized use of Genozip.",

    "5. Data collected",
    "   a. At registration time: registration information provided by you and details about your hardware, operating system and IP address as displayed at end of the registration process and confirmed by you.",
    "   b. Non-paid licenses only: When a file is compressed: aggregate statistical information about the performance of the compression algorithm and associated metadata. Details can be found here: " WEBSITE_STATS". This information is not collected when using Genozip with a paid license.",
 
    "6. Trademarks. This License does not grant permission to use the trade names, trademarks, service marks, or product names of the Licensor, except as required for reasonable and customary use in describing the origin of the Genozip",
    
    "7. Disclaimer of Warranty. Unless required by applicable law or agreed to in writing, Licensor provides Genozip on an \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied, including, without limitation, any warranties or conditions of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE. You are solely responsible for determining the appropriateness of using or redistributing the Genozip and assume any risks associated with Your exercise of permissions under this License.",
    
    "8. Limitation of Liability. In no event and under no legal theory, whether in tort (including negligence), contract, or otherwise, unless required by applicable law (such as deliberate and grossly negligent acts) or agreed to in writing, shall Licensor or Developer be liable to You for damages, including any direct, indirect, special, incidental, or consequential damages of any character arising as a result of this License or out of the use or inability to use Genozip (including but not limited to damages for loss of goodwill, work stoppage, computer failure or malfunction, file corruption, data loss, or any and all other commercial damages or losses), even if Licensor or Developer have been advised of the possibility of such damages.",
    "END OF TERMS AND CONDITIONS",

    LIC_FIELD_VERSION ": " GENOZIP_CODE_VERSION 
};
 