// ------------------------------------------------------------------
//   text-license.h
//   Copyright (C) 2019-2021 Divon Lan <divon@genozip.com>
//   Please see terms and conditions in the files LICENSE.non-commercial.txt and LICENSE.commercial.txt

static const char *license[] = {
    "This program, \"Genozip\", and all associated, source code, object code, documentation and other files, are copyright (C) 2019-2021 Divon M Lan (\"Copyright Owner\"). All rights reserved.",
    "This license is limited in scope, and covers NON-COMMERCIAL and some other limited use cases as described below.",
    "For a commercial license, please contact sales@genozip.com",
    "Acknowledgement: portions of the text of this license are based on Apache License 2.0, however it differs from it substantially",
    "TERMS AND CONDITIONS FOR USE",
    "1. Definitions.",
    "\"License\" shall mean the terms and conditions for use as defined by Sections 1 through 7 of this document.",
    "\"Licensor\" shall mean Copyright Owner or entity authorized by Copyright Owner that is granting the License.",
    "\"Legal Entity\" shall mean the union of the acting entity and all other entities that control, are controlled by, or are under common control with that entity. For the purposes of this definition, \"control\" means (i) the power, direct or indirect, to cause the direction or management of such entity, whether by contract or otherwise, or (ii) ownership of fifty percent (50%) or more of the outstanding shares, or (iii) beneficial ownership of such entity.",
    "\"You\" (or \"Your\") shall mean an individual or Legal Entity exercising permissions granted by this License.",
    "\"Source\" form shall mean the preferred form for making modifications, including but not limited to software source code, documentation source, and configuration files.",
    "\"Object\" form shall mean any form resulting from mechanical transformation or translation of a Source form, including but not limited to compiled object code, generated documentation, and conversions to other media types.",
    "\"Executable\" shall mean a type of Object, for which there exists an operating system of a computing device, for which said operating system is capable of running said Object as an operating system process.",
    "\"Work\" shall mean the work of authorship, whether in Source or Object form, made available under the License, as indicated by a copyright notice that is included in or attached to the work.",
    "\"Derivative Works\" shall mean any work, whether in Source or Object form, that is based on (or derived from) the Work and for which the editorial revisions, annotations, elaborations, or other modifications represent, as a whole, an original work of authorship. For the purposes of this License, Derivative Works shall not include works that remain separable from, or merely link (or bind by name) to the interfaces of, the Work and Derivative Works thereof.",
    "2. Grant of Copyright License. Subject to the terms and conditions of this License, Licensor hereby grants to You a perpetual, worldwide, non-exclusive, no-charge, royalty-free, revocable copyright license to reproduce, publicly display, publicly perform, and distribute the Work in Source or Object form (together: \"Using\"), subject to the following details:",
    "   a. This license does NOT permit creation of Derivative Works, and does not permit distributing modified Source or Object based on modified Source",
    "   b. This license does NOT permit Using the features of the Work intended for compressing data, including the genozip Executable, for any purpose except b1,b2,b3,b4 hereinafter if (i) You are a commercial entity or Your work involving using Genozip is on behalf or for the benefit of a commercial entity; and/or (ii) the use of the Work is in the context of work that has ultimate commerical goals; and/or (iii) a client is paying You for the work that includes the usage of Genozip. If you are uncertain about whether your case would fall into these categories, please enquire with register@genozip.com.",
    "      b1. This license DOES permit Using the Work for academic research that lacks ultimate commercial goals, and/or for educational purposes and/or for training purposes, including by a commerical entity.",
    "      b2. This license DOES permit Using the Work for the purpose of evaluating it for a duration of 30 days, including by a commerical entity.",
    "      b3. This license DOES permit Using the Work for the purpose of distributing it to others in unmodified Source form or Object derived from unmodified Source, and including this License via a platform that is both publicly accessible and free of charge, including but not limited to an Internet website",
    "      b4. This license DOES permit Using, including reproducing and distributing, the three Executables genounzip, genocat and genols for any purpose including commercial.",
    "   c. This license DOES NOT permit compressing a file, unless the file is retained in its original form as well or the potential loss of data due to Genozip not being able to uncompress the compressed file would not cause any harm.",
    "   d. This license is conditional on You fully and accurately completing the registration, either by completing the registeration flow as prompted by an Executable of the Work, or by receiving registration confirmation after registering by emailing register@genozip.com.",
    "3. Severe non-compliance. Violation of section 2.b. and/or 2.d. is considered severe non-compliance with this non-commercial license. In this case, Licensor claims, and You hereby agree to, equally shared ownership with Licensor of any revenue generated and/or any intellectual property created that involved the non-compliant use of Genozip. If you are reviewing this license and concerned that this section might apply to you, please review our commercial license options at http://genozip.com/commercial.html",
    "4. Submission of Contributions. Unless You explicitly state otherwise, any software source code intentionally submitted for inclusion in the Work by You to the Licensor shall imply complete and irrevocable assignment by You to Copyright Owner of all copyright in the submitted source code.",
    "5. Trademarks. This License does not grant permission to use the trade names, trademarks, service marks, or product names of the Licensor, except as required for reasonable and customary use in describing the origin of the Work",
    "6. Disclaimer of Warranty. Unless required by applicable law or agreed to in writing, Licensor provides the Work on an \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied, including, without limitation, any warranties or conditions of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE. You are solely responsible for determining the appropriateness of using or redistributing the Work and assume any risks associated with Your exercise of permissions under this License.",
    "7. Limitation of Liability. In no event and under no legal theory, whether in tort (including negligence), contract, or otherwise, unless required by applicable law (such as deliberate and grossly negligent acts) or agreed to in writing, shall Licensor or Copyright Owner be liable to You for damages, including any direct, indirect, special, incidental, or consequential damages of any character arising as a result of this License or out of the use or inability to use the Work (including but not limited to damages for loss of goodwill, work stoppage, computer failure or malfunction, file corruption, data loss, or any and all other commercial damages or losses), even if Licensor or Copyright Owner has been advised of the possibility of such damages.",
    "END OF TERMS AND CONDITIONS",
};
