Bootstrap:docker  
From:ubuntu

%labels
    Maintainer divonlan

%help
Help me. I'm in the container.

%environment
    PATH=/genozip:${PATH}
    export PATH

%post
    echo "Installing genozip into container..."

    # Here we are at the base, /, of the container
    git clone https://github.com/divonlan/genozip.git
    cd /genozip
    make
    
%runscript
    exec /genozip/genozip "$@"

# apps

%apprun genozip
    exec /genozip/genozip "$@"

%apprun genounzip
    exec /genozip/genounzip "$@"

%apprun genocat
    exec /genozip/genocat "$@"

%apprun genols
    exec /genozip/genols "$@"

%apphelp genozip
    This is the help for genozip app.

%apphelp genounzip
    This is the help for genounzip app.

%apphelp genocat
    This is the help for genocat app.

%apphelp genols
    This is the help for genols app.

