#!/usr/bin/bash 

# ------------------------------------------------------------------
#   flags_assign.sh
#   Copyright (C) 2026-2026 Genozip Limited. Patent Pending.
#   Please see terms and conditions in the file LICENSE.txt
#
#   WARNING: Genozip is proprietary, not open source software. Modifying the source code is strictly prohibited
#   and subject to penalties specified in the license.

# assign integer flags to boolean members of flag struct

out=flags_assign.c

members=`grep "#define _" flags.c | grep "&fint" | cut -d"." -f2 | cut -d, -f1 | sort | uniq`

cat > $out << END
// ------------------------------------------------------------------
//   flags_assign.c
//   Copyright (C) 2026-2026 Genozip Limited. Patent Pending.
//   Please see terms and conditions in the file LICENSE.txt
//
//   WARNING: Genozip is proprietary, not open source software. Modifying the source code is strictly prohibited
//   and subject to penalties specified in the license.
//
//   AUTO-GENERATED by flags_assign.sh

struct { int $(echo $members | sed "s/ /, /g"); } fint = {}; /* temporary int flags */

#define FLAGS_ASSIGN_BOOL \\
$(for m in $members; do printf "    if (fint.$m) flag.$m = fint.$m; \\" ; echo ; done)

END
# ^^ empty line to terminate final backslash
