// ------------------------------------------------------------------
//   sam_gem3.c
//   Copyright (C) 2022-2023 Genozip Limited. Patent pending.
//   Please see terms and conditions in the file LICENSE.txt
//
//   WARNING: Genozip is proprietary, not open source software. Modifying the source code is strictly prohibited,
//   under penalties specified in the license.

// Compresses auxilliary fields generated by gem3 mapper

#include "genozip.h"
#include "sam_private.h"
#include "strings.h"
#include "reference.h"
#include "segconf.h"
#include "seg.h"
#include "piz.h"
#include "reconstruct.h"
#include "lookback.h"

// ----------------------------------------------------------------------------------------------
// XB:A gem3: the version of the reference to which the read is mapped (either CT or GA)
// Two possible values: 'C' or 'G' http://dcc.blueprint-epigenome.eu/#/md/bs_seq_grch38
// ----------------------------------------------------------------------------------------------

// 2 possible values: G C
void sam_seg_gem3_XB_A (VBlockSAMP vb, ZipDataLineSAM *dl, STRp(xb), unsigned add_bytes)
{
    ASSSEG (xb_len==1 && (xb[0]=='C' || xb[0]=='G'), "Invalid XB:A=%.*s, expecting C or G", STRf(xb));

    if (vb->bisulfite_strand)
        seg_by_did (VB, (char[]){ SNIP_SPECIAL, SAM_SPECIAL_GEM3_XB }, 2, OPTION_XB_A, add_bytes);

    else 
        seg_by_did (VB, xb, 1, OPTION_XB_A, add_bytes);
}

SPECIAL_RECONSTRUCTOR (sam_piz_special_GEM3_XB)
{
    ASSPIZ0 (VB_SAM->bisulfite_strand, "XB:A cannot be reconstructed because bisulfite_strand is not known - likely SEQ was not reconstructed");
    
    if (reconstruct) 
        RECONSTRUCT1 (VB_SAM->bisulfite_strand);

    return NO_NEW_VALUE;
}

// ------------------------------------------------------------------------
// XA:Z "Alternative alignments" (a BWA, gem3 feature)
// In gem3, when used with --bisulfite XA includes the XB of each alignment
// Example: XA:Z:chr1,+G10006,103M1I36M1D11M,9;
//                     ^
// ------------------------------------------------------------------------

// split the pos strand-XB-pos string (generated with --bisulfite), eg "-C10000" to strand "-" XB "C" and pos "10000"
bool sam_seg_gem3_XA_strand_cb (VBlockP vb, ContextP ctx, STRp(field), uint32_t rep)
{
    char strand = field[0];
    char xb     = field[1];

    if (field_len != 2 || (strand != '+' && strand != '-') || (xb != 'C' && xb != 'G'))  
        return false; // invalid XA format 

    // seg normally for now, we might change it in sam_seg_BWA_XA_pos
    WordIndex strand_index = (2 + ((strand=='+') | (xb=='G') << 1));
    seg_known_node_index (vb, CTX (OPTION_XA_STRAND), strand_index, 2); 

    return true; // segged successfully
}
