// ------------------------------------------------------------------
//   sam_cpu.c
//   Copyright (C) 2024-2026 Genozip Limited. Patent pending.
//   Please see terms and conditions in the file LICENSE.txt
//
//   WARNING: Genozip is proprietary, not open source software. Modifying the source code is strictly prohibited,
//   under penalties specified in the license.

// Compresses auxilliary fields generated by tmap (IonXpress) mapper

#include "sam_private.h"

static rom xl_prediction (bool line_has_XM)
{
    return line_has_XM ? "aln" : "mem";
}

void sam_seg_CPU_XL_Z (VBlockSAMP vb, STRp(xl), unsigned add_bytes)
{
    decl_ctx (OPTION_XL_Z);

    if (str_issame_(STRa(xl), xl_prediction (has(XM_i)), 3))
        seg_special0 (VB, SAM_SPECIAL_CPU_XL, ctx, add_bytes);

    else 
        seg_by_ctx (VB, STRa(xl), ctx, add_bytes);
}

// since 15.0.65
SPECIAL_RECONSTRUCTOR (sam_piz_special_CPU_XL)
{
    if (reconstruct) {
        rom prediction = xl_prediction (curr_container_has (vb, _OPTION_XM_i));
        RECONSTRUCT (prediction, 3);
    }

    return NO_NEW_VALUE;
}
