// ------------------------------------------------------------------
//   sam_tmap.c
//   Copyright (C) 2022-2024 Genozip Limited. Patent pending.
//   Please see terms and conditions in the file LICENSE.txt
//
//   WARNING: Genozip is proprietary, not open source software. Modifying the source code is strictly prohibited,
//   under penalties specified in the license.

// Compresses auxilliary fields generated by tmap (IonXpress) mapper

#include "sam_private.h"

void sam_seg_TMAP_XM_i (VBlockSAMP vb, ValueType XM, unsigned add_bytes)
{
    // XM is predicted to be ref_consumed
    if (XM.i == vb->ref_consumed)                              
        seg_by_did (VB, (char[]){ SNIP_SPECIAL, SAM_SPECIAL_REF_CONSUMED }, 2, OPTION_XM_i, add_bytes);
        
    else
        seg_integer (VB, CTX(OPTION_XM_i), XM.i, true, add_bytes);
}

