// ------------------------------------------------------------------
//   sam_tmap.c
//   Copyright (C) 2022-2024 Genozip Limited. Patent pending.
//   Please see terms and conditions in the file LICENSE.txt
//
//   WARNING: Genozip is proprietary, not open source software. Modifying the source code is strictly prohibited,
//   under penalties specified in the license.

// Compresses auxilliary fields generated by tmap (IonXpress) mapper

#include <math.h>
#include "sam_private.h"

void sam_seg_tmap_XM_i (VBlockSAMP vb, int64_t xm, unsigned add_bytes)
{
    decl_ctx (OPTION_XM_i);

    // xm is predicted to be ref_consumed
    if (xm == vb->ref_consumed)                              
        seg_special0 (VB, SAM_SPECIAL_REF_CONSUMED, ctx, add_bytes);
        
    else
        seg_integer (VB, ctx, xm, true, add_bytes);
}

static int64_t xt_prediction (int64_t as)
{
    return round ((double)as * 0.2510174851 - 3.192195876); // based on AS vs XT regression in test.ion-cardiomyopathy.bam
}

void sam_seg_tmap_XT_i (VBlockSAMP vb, ZipDataLineSAMP dl, int64_t xt, unsigned add_bytes)
{
    decl_ctx (OPTION_XT_i);

    if (has(AS_i)) {
        int64_t delta = xt - xt_prediction (dl->AS);

        seg_special1 (VB, SAM_SPECIAL_TMAP_XT, '1'/*method version*/, ctx, add_bytes);
        seg_integer (VB, ctx, delta, false, 0);
    }

    else
        seg_integer (VB, ctx, xt, true, add_bytes);
}

SPECIAL_RECONSTRUCTOR (sam_piz_special_TMAP_XT)
{
    int64_t as = reconstruct_peek (VB, CTX(OPTION_AS_i), 0, 0).i;
    int64_t delta = reconstruct_from_local_int (vb, ctx, 0, RECON_OFF);

    new_value->i = xt_prediction (as) + delta;

    if (reconstruct) RECONSTRUCT_INT (new_value->i);

    return HAS_NEW_VALUE;
}

